# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2020-09-21T11:04:09+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class ExampleTle(BaseModel):
    id: str
    mid_level_element: Optional[Dict[str, Any]] = Field(
        None,
        alias='mid-level-element',
        description='a whitty description.',
        title='Title',
    )


class ExampleElement(BaseModel):
    id: str
    value: str


class Model(BaseModel):
    example_tle: ExampleTle = Field(..., alias='example-tle')
